name: ceylife_digital
description: Ceylinco Life Mobile Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.2+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.1.1
  get_it: ^5.0.3
  equatable: ^1.2.5
  dartz: ^0.9.2
  flutter_svg: ^0.19.1
  dio: ^3.0.10
  intl: ^0.16.1
  shared_preferences: ^0.5.12+4
  package_info: ^0.4.3+2
  firebase_core: ^0.5.3
  firebase_messaging: ^7.0.3
  flutter_udid: ^1.0.1
  after_init: ^0.1.2
  smooth_page_indicator: ^0.2.0
  google_maps_flutter: ^1.1.1
  url_launcher: ^5.7.10
  map_launcher: ^1.1.2
  pinch_zoom: ^0.0.4
  photo_view: ^0.10.3
  device_info: ^1.0.0
  otp_count_down: ^1.0.6
  lottie: ^0.7.0+1
  progress_dialog: ^1.2.4
  crypto: ^2.1.5
  camera: ^0.7.0+2
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+22
  path_provider: ^1.6.27
  permission_handler: ^5.1.0+2
  easy_permission_validator: ^2.0.1
  flutter_screenutil: ^4.0.3+3
  flutter_downloader: ^1.5.2
  flutter_swiper: ^1.1.6
  flutter_masked_text: ^0.8.0
  flutter_local_notifications: ^4.0.1+2
  pull_to_refresh: 1.6.3
  flutter_material_color_picker: ^1.0.5
  flutter_statusbarcolor: ^0.2.3
  marquee_widget: ^1.0.0
  flutter_inappwebview: ^4.0.0+4
  provider: ^4.3.3
  connectivity: ^2.0.2
  flutter_secure_storage: ^3.3.5
  installer_info: ^0.2.0
  pointycastle: ^1.0.1
  encrypt: ^3.3.1
  hex: ^0.1.2
  xor: ^0.2.2
  http_certificate_pinning: 1.0.4
  date_format: ^1.0.8
  string_validator: ^0.1.4
  trust_fall: ^1.0.4
  local_auth: ^0.6.3+4
  open_appstore: ^1.0.2
  file_picker: ^2.1.6
  open_file: ^3.0.3

  #Huawei
  huawei_push: ^5.0.2+301
  huawei_map: ^5.0.3+302

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/pngs/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - images/svgs/
    - images/pngs/
    - locales/
    - animation/
  fonts:
    - family: SohoGothicPro
      fonts:
        - asset: fonts/SohoGothicPro-Regular.ttf
        - asset: fonts/SohoGothicPro-Bold.ttf
          weight: 700
        - asset: fonts/SohoGothicPro-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/SohoGothicPro-ExtraBold.ttf
          weight: 800
        - asset: fonts/SohoGothicPro-ExtraBoldIt.ttf
          style: italic
          weight: 800
        - asset: fonts/SohoGothicPro-Light.ttf
          weight: 300
        - asset: fonts/SohoGothicPro-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/SohoGothicPro-Medium.ttf
          weight: 500
        - asset: fonts/SohoGothicPro-MediumIt.ttf
          weight: 500
          style: italic
        - asset: fonts/SohoGothicPro-Thin.ttf
          weight: 100
        - asset: fonts/SohoGothicPro-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/SohoGothicPro-Italic.ttf
          style: italic
    - family: FMEmanee
      fonts:
        - asset: fonts/FMEmanee.ttf
    - family:  CeylifeIcons
      fonts:
        - asset: fonts/CeylifeIcons.ttf