enum Flavor { DEV, UAT, QA, LIVE }
enum AlertType { SUCCESS, FAIL }
enum ButtonType { ENABLED, DISABLED }
enum InfoType { NAME, EMAIL, NIC, DOB, MOBILE, ADDRESS }
enum PolicyStatus { ACTIVE, LAPSED, PAIDUP, PROPOSAL, MATURED, BUYONLINE }
enum DirectPayStatus { SUCCESS, FAILED }
enum NotificationType { NEWS, PROMO }
enum SecurityFailureType { ADB, ROOT, EMU, SECURE, SOURCE}
enum Biometric{FINGERPRINT, FACE, BOTH, NONE}
enum SignInType{PASSWORD, BIOMETRIC}
enum Languages {ENGLISH, SINHALA, TAMIL}
enum DrawerItem {
  PAYMENT_HISTORY,
  CUSTOMER_SERVICE_REQUEST,
  SETTINGS,
  LANGUAGE_SELECTION,
  PASSWORD_RESET,
  BRANCH_LOCATOR,
  CONTACT_US,
  FAQ,
  FEATURE1,
  FEATURE2,
}
enum EmptyStatus {
  NEWS,
  PAYMENT_HISTORY,
  CUSTOMER_SERVICE_REQUEST,
  NOTIFICATIONS,
  PROMOTIONS,
  PRODUCT_DETAILS,
  BENEFITS,
  LOAD_DETAIL,
  HEALTH_TIPS,
  RATE_HISTORY
}
